version: '3.8'
services:
  gateway:
    image: eco_tourism_gateway
    build:
      context: ./eco_tourism_gateway
    ports:
      - "8090:80"
    networks:
      - eco_tourism_network

  user:
    image: eco_tourism_user
    build:
      context: ./eco_tourism_user
    ports:
      - "8091:80"
    networks:
      - eco_tourism_network

  tourist:
    image: eco_tourism_tourist
    build:
      context: ./eco_tourism_tourist
    ports:
      - "8092:80"
    networks:
      - eco_tourism_network

  accommodation:
    image: eco_tourism_accommodation
    build:
      context: ./eco_tourism_accommodation
    ports:
      - "8093:80"
    networks:
      - eco_tourism_network

  weather:
    image: eco_tourism_weather
    build:
      context: ./eco_tourism_weather
    ports:
      - "8094:80"
    networks:
      - eco_tourism_network  

  outdoor:
    image: eco_tourism_outdoor
    build:
      context: ./eco_tourism_outdoor
    ports:
      - "8095:80"
    networks:
      - eco_tourism_network  

networks:
  eco_tourism_network:
    driver: bridge
